# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'
    - run: sed -i 's/GYMPASS_USER/${{ secrets.GYMPASS_USER }}/g' cypress.env.json
    - run: sed -i 's/GYMPASS_PASSWORD/${{ secrets.GYMPASS_PASSWORD }}/g' cypress.env.json
    - run: npm ci
    - name: Run Book
      id: run_book
      run: |
        if npm run book; then
          echo "::set-output name=result::true"
        else
          echo "::set-output name=result::false"
        fi
    - if: steps.run_book.outputs.result == 'false'
      run: npm run checkin
