# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: book

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '20 9 * * 1,3,5'
    - cron: '20 10 * * 2,4'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'
    - run: sed -i 's/GYMPASS_USER/${{ secrets.GYMPASS_USER }}/g' cypress.env.json
    - run: sed -i 's/GYMPASS_PASSWORD/${{ secrets.GYMPASS_PASSWORD }}/g' cypress.env.json
    - run: npm ci
    - run: npm run book
